### Update the lines below with the appropriate information, then save as lando.yml ###

name: #local-site-name (can be whatever you'd like)

config:
  site: #pantheon-site-name-goes-here
  id: #pantheon-site-id-goes-here
