#!/bin/bash
set -eo pipefail

## Site specific environment variables.
## If needing to override the defaults, put this in the site root
## as `set-environment` with chmod +x.

(
  echo "THEME_DIR=web/wp-content/themes/wordpressci"
  echo "NPM_VER=16.x"
  echo "PHP_VER=7.4"
) >> $GITHUB_ENV
